# .github/workflows/depuracion-manual-ssh.yml
name: Depuración Manual con tmate (SSH)

on:
  # Permite iniciar el workflow manualmente
  workflow_dispatch:

jobs:
  sesion-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar sesión de tmate para acceso SSH
        run: |
          # 1. Instala tmate
          sudo apt-get update
          sudo apt-get install -y tmate

          # 2. Inicia tmate y mantiene la sesión abierta
          echo "-------------------------------------------------------------------"
          echo "Iniciando tmate... La conexión SSH puede tardar un minuto en aparecer."
          echo "Copia la línea que empieza con 'ssh' y pégala en tu terminal (Termux)."
          echo "La sesión permanecerá activa hasta que cierres el workflow en GitHub."
          echo "-------------------------------------------------------------------"
          tmate -F
